const CACHE="infinite-arts-web-1caf01d708950785";const FILES=["./app-icon.png", "./index.html", "./manifest.webmanifest", "./update-source.json", "./assets/archer.svg", "./assets/bear.svg", "./assets/cat.svg", "./assets/chicken.svg", "./assets/cow.svg", "./assets/dog.svg", "./assets/dragon.svg", "./assets/duck.svg", "./assets/eagle.svg", "./assets/flying-sword.svg", "./assets/goblin.svg", "./assets/golem.svg", "./assets/ground.svg", "./assets/horse.svg", "./assets/imp.svg", "./assets/index-DLIrICUa.js", "./assets/index-jivBR8pT.css", "./assets/infinite-sigil.svg", "./assets/mage.svg", "./assets/pig.svg", "./assets/rabbit.svg", "./assets/sheep.svg", "./assets/slime.svg", "./assets/sorcerer.svg", "./assets/tiger.svg", "./assets/wolf.svg", "./assets/expansion/angel.svg", "./assets/expansion/demon.svg", "./assets/expansion/dinosaur.svg", "./assets/expansion/elephant.svg", "./assets/expansion/elf.svg", "./assets/expansion/fire_elemental.svg", "./assets/expansion/head.svg", "./assets/expansion/ice_elemental.svg", "./assets/expansion/lightning_elemental.svg", "./assets/expansion/lion.svg", "./assets/expansion/paw.svg", "./assets/expansion/phoenix.svg", "./assets/expansion/reaper.svg", "./assets/expansion/robot.svg", "./assets/expansion/skeleton.svg", "./assets/expansion/snake.svg", "./assets/expansion/spider.svg", "./assets/expansion/treant.svg", "./assets/expansion/trex.svg", "./assets/expansion/water_elemental.svg", "./assets/expansion/zombie.svg", "./assets/fantasy/ART.md", "./assets/fantasy/characters.png", "./assets/fantasy/companions.png", "./assets/fantasy/elements.png", "./assets/fantasy/environment.png", "./assets/fantasy/fireball.png", "./assets/fantasy/fist.png", "./assets/fantasy/ground.png", "./assets/fantasy/hero-walk.png", "./assets/fantasy/items.png", "./assets/fantasy/mahoraga.png", "./assets/fantasy/spells.png", "./assets/fantasy/susanoo.png", "./assets/fantasy/vfx-v2.png", "./assets/fantasy/walk-a.png", "./assets/fantasy/walk-b.png", "./assets/fantasy/walk-c.png"];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(FILES))));
self.addEventListener('message',event=>{if(event.data==='ACTIVATE')self.skipWaiting();});
self.addEventListener('activate',event=>event.waitUntil(Promise.all([caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('infinite-arts-web-')&&k!==CACHE).map(k=>caches.delete(k)))),self.clients.claim()])));
self.addEventListener('fetch',event=>{
 const url=new URL(event.request.url);
 if(event.request.method!=='GET'||url.origin!==self.location.origin||url.pathname.endsWith('/web-build.json')||url.pathname.endsWith('/sw.js'))return;
 event.respondWith(caches.open(CACHE).then(async cache=>{
  const key=event.request.mode==='navigate'?new URL('./index.html',self.location.href).href:event.request;
  const hit=await cache.match(key);return hit||fetch(event.request);
 }));
});
